### ISSUE TITLE
About documents of model training and data preprocessing.

### ISSUE THREAD

**Issue by WindVChen** [zkf1997/DIMOS#4]
Hi, 

It's a great work! 

May I know if the model training and data preprocessing documents will be updated soon?

**Comment by zkf1997** [comment]
Thanks for reaching out. I started working on the train & data release earlier this month, it will be out soon. I will reply in this thread when it's released.

**Comment by WindVChen** [comment]
Thanks for the reply. Looking forward to it :)

**Comment by Jiaqi-zhang** [comment]
Hello, thanks for your work.
Could you please tell me if you use the Isaac Gym platform for simulations during training? And how are scenarios like those in ShapeNet added to the environment for simulated training? Thanks!

**Comment by zkf1997** [comment]
> Hello, thanks for your work. Could you please tell me if you use the Isaac Gym platform for simulations during training? And how are scenarios like those in ShapeNet added to the environment for simulated training? Thanks!

Hi, as a pure kinematic method, we do not use physics simulators like Isaac Gym in this paper.  

Best

**Comment by zkf1997** [comment]
I just pushed the description of data preprocessing and training. Please let me know if you have any questions or get into problems.

**Comment by WindVChen** [comment]
Thanks much for the notice!

**Comment by WindVChen** [comment]
Hi @zkf1997 ,

I am not very familiar with the SMPLX model. May I know how you add texture to the human (as displayed on your project website)? I have tried the following code; however, there seem some inconsistent seams in the results:

```python
from PIL import Image
from io import BytesIO
texture_file_name = r'C:\Users\PC\Desktop\SMPL-NeRF-textures\smplx_texture_f_alb.png'

with open(texture_file_name, 'rb') as file:
  texture = Image.open(BytesIO(file.read()))

objPath = r'G:\Datasets\SMPL\smplx_uv\smplx_uv.obj'

obj = trimesh.load(objPath)
obj.merge_vertices(merge_tex=True)
# get uv map
uv = obj.visual.uv
# Convert to numpy array
uv = np.array(uv)

...

m = trimesh.Trimesh(vertices=vertices[seq_idx], faces=body_model.faces, visual=trimesh.visual.TextureVisuals(uv=uv, image=texture), process=False)

...
```

Unsatisfactory result:
![image](https://github.com/zkf1997/DIMOS/assets/56162412/6181558a-1e00-470b-93a0-a38aef93aff0)

**Comment by zkf1997** [comment]
For the visualization on the website, I used the smplx blender addon and rendered in blender. For blender visualization, you can refer to this reply: https://github.com/zkf1997/DIMOS/issues/3#issuecomment-1771681207 
I did not try to add texture using trimesh.
