### ISSUE TITLE
Where can I get "{prox_scene}_segment.json"?

### ISSUE THREAD

**Issue by teshima058** [zkf1997/DIMOS#7]
When I tried to run `python synthesize/get_scene.py`, I noticed that the file 'data/proxs/scenes_semantics/BasementSittingBooth_segment.json' was missing.
According to the COINS page, the scene_semantics files seems to be available from the PROX-E project, but in [the downloadable files](https://github.com/yz-cnsdqz/PSI-release?tab=readme-ov-file#:~:text=PROX%2DE%20can%20be%20downloaded%20here.), I could not find the {prox_scene_name}_segment.json file in the scene_semantics folder.
Would you please tell me how to obtain these json files?

**Comment by zkf1997** [comment]
*_segment.json files are provided in COINS, you can check here: https://drive.google.com/drive/u/1/folders/1-vwuZTAhpN3ifzYJLEnKwn5yxHlq_sHr

**Comment by teshima058** [comment]
Thanks!
